kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${project.artifactId}
  annotations:
    app.openshift.io/connects-to: ${db.type}-db
  labels:
    app.kubernetes.io/part-of: fruit-service-app
    app.openshift.io/runtime: spring
spec:
  template:
    spec:
      containers:
        - env:
            - name: SERVICE_DB_USER
              valueFrom:
                secretKeyRef:
                   name: ${project.artifactId}-${db.type}-db
                   key: DB_USER
            - name: SERVICE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${project.artifactId}-${db.type}-db
                  key: DB_PASSWORD
            - name: SERVICE_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ${project.artifactId}-${db.type}-db
                  key: DB_NAME
            - name: SERVICE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ${project.artifactId}-${db.type}-db
                  key: DB_HOST
            - name: JAVA_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: ${project.artifactId}-${db.type}-configmap
                  key: java-options
