---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ora-startup193
  labels:
    app: database
    version: 19.3.0.1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ora-setup193
  labels:
    app: database
    version: 19.3.0.1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ora-data193
  labels:
    app: database
    version: 19.3.0.1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 20Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: oradb
data:
  DB_MEMORY: 4g
  DB_BUNDLE: basic
  DB_DOMAIN: localdomain
  DB_SID: PSTG
  DB_PDB: PSTGPDB1
  ORACLE_SID: ORCL
  ORACLE_PDB: ORCLPDB1
  ORACLE_CHARACTERSET: AL32UTF8
  ORACLE_PWD: 'Kube#2020'
  DB_PASSWD: 'Kube#2020'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
  labels:
    app: database
    version: 19.3.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 19.3.0.1
  template:
    metadata:
      name: oracle-db
      labels:
        app: database
        version: 19.3.0.1
    spec:
      securityContext:
        fsGroup: 54321
      volumes:
         - name: dshm
           emptyDir:
             medium: Memory  
         - name: ora-data193
           persistentVolumeClaim:
             claimName: ora-data193
         - name: ora-startup193
           persistentVolumeClaim:
             claimName: ora-startup193
         - name: ora-setup193
           persistentVolumeClaim:
             claimName: ora-setup193
      containers:
        - name: oracle
          #image: registry:32000/oracledb:19.3.0-ee
          image: container-registry.oracle.com/database/enterprise:19.3.0.0
          command:
          - /opt/oracle/runOracle.sh
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 4Gi
          ports:
            - name: listener
              containerPort: 1521
              hostPort: 1521
            - name: oemexpress
              containerPort: 5500
              hostPort: 5500
          volumeMounts:
            - name: dshm
              mountPath: "/dev/shm"
            - name: ora-data193
              mountPath: "/opt/oracle/oradata"
            - name: ora-setup193
              mountPath: "/opt/oracle/scripts/setup"
            - name: ora-startup193
              mountPath: "/opt/oracle/scripts/startup"
          #readinessProbe:
          #  initialDelaySeconds: 60
          #  periodSeconds: 60
          #  exec:
          #    command:
          #      - /bin/sh
          #      - "-c"
          #      - $ORACLE_BASE/$CHECK_DB_FILE
          #livenessProbe:
          #  initialDelaySeconds: 30
          #  periodSeconds: 60
          #  exec:
          #    command:
          #      - /bin/sh
          #      - "-c"
          #      - $ORACLE_BASE/$CHECK_DB_FILE
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","@echo shutdown immediate | sqlplus / as sysdba"]
          env:
            - name: ORACLE_SID
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_SID #Read the key call ORALCE_SID
            - name: ORACLE_PDB
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PDB #Read the key call ORACLE_PDB
            - name: ORACLE_PWD
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PWD #Read the key call ORACLE_PWD
            - name: ORACLE_CHARACTERSET
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_CHARACTERSET #Read the key call ORACLE_CHARACTERSET
      imagePullSecrets:
        - name: oracle-registry
---
# Headless Service, returns the IPs of the PODs directly, not a virtual IP
apiVersion: v1
kind: Service
metadata:
  name: oracle-db
  labels:
    app: database
    version: 19.3.0.1
spec:
  selector:
    app: database
    version: 19.3.0.1
  type: ClusterIP
  ports:
  - name: listener
    protocol: TCP
    port: 1521
    targetPort: 1521
  - name: oemexpress
    protocol: TCP
    port: 5500
    targetPort: 5500
